AM.UI.WEB/Controllers/FlightController.cs
using Microsoft.AspNetCore.Http;
using System.IO;

using Microsoft.AspNetCore.Mvc;
using AM.ApplicationCore.Interfaces;
using AM.ApplicationCore.Domain;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace AM.UI.WEB.Controllers
{
    public class FlightController : Controller
    {
        private readonly IServiceFlight _flightService;
        private readonly IServicePlane _planeService;

        public FlightController(IServiceFlight flightService,IServicePlane planeService)
        {
            _planeService = planeService;
            _flightService = flightService;
        }

        // GET: FlightController
        public ActionResult Index(DateTime? dateDepart)
        {

            if (dateDepart == null)
            {
                return View(_flightService.GetAll().ToList());
            }
            else
            {
                
                return View(_flightService.GetFlightByDate(((DateTime)dateDepart)));
            }
        }

        // GET: FlightController/Details/5
        public ActionResult Details(int id)
        {

            var flight = _flightService.GetById((int)id);
            if (flight == null)
            {
                return NotFound();
            }
            return View(flight);
        }

        // GET: FlightController/Create
        public ActionResult Create() { 
            ViewBag.Planes = new SelectList(_planeService.GetAll().ToList(),
                "PlaneId", "Information");
            return View();
        }

        // POST: FlightController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Flight flight, IFormFile AirlineImage)
        {
            
            try
            {
                if (AirlineImage != null)
                {
                    var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "uploads", AirlineImage.FileName);
                    Stream stream = new FileStream(path, FileMode.Create);
                    AirlineImage.CopyTo(stream);
                    flight.Airline = AirlineImage.FileName;
                }
                _flightService.Add(flight);
                _flightService.Commit();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: FlightController/Edit/5
        public ActionResult Edit(int? id)
        {
            
            if (id == null)
            {
                return NotFound();
            }

            var flight = _flightService.GetById((int)id);
            if (flight == null)
            {
                return NotFound();
            }
            
            ViewBag.Planes = new SelectList(_planeService.GetAll().ToList(),
                "PlaneId", "Information", flight.PlaneId);
            return View(flight);
        }

        // POST: FlightController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Flight flight)
        {
            try
            {
                _flightService.Update(flight);
                _flightService.Commit();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
           
        }

        // GET: FlightController/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var flight = _flightService.GetById((int)id);
            if (flight == null)
            {
                return NotFound();
            }

            return View(flight);
        }

        // POST: FlightController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            try
            {
                var flight = _flightService.GetById((int)id);
                _flightService.Delete(flight);
                _flightService.Commit();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

AM.UI.WEB/Controllers/PlaneController.cs
using AM.ApplicationCore.Domain;
using AM.ApplicationCore.Interfaces;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace AM.UI.WEB.Controllers
{
    public class PlaneController : Controller
    {
        private readonly IServicePlane _planeService;

        public PlaneController(IServicePlane planeService)
        {
            _planeService = planeService;
        }
        // GET: PlaneController
        public ActionResult Index()
        {
            //return View();

            List<Plane> listplane = _planeService.GetAll().ToList();
            foreach (var plane in listplane)
            {
                plane.NbrVols = _planeService.GetFlightNbre(plane);
            }

            return View(listplane);
        }

        // GET: PlaneController/Details/5
        public ActionResult Details(int id)
        {
            var plane = _planeService.GetById((int)id);
            if (plane == null)
            {
                return NotFound();
            }
            return View(plane);
        }

        public ActionResult _Details(int id)
        {
            var plane = _planeService.GetById((int)id);
            if (plane == null)
            {
                return NotFound();
            }
            return PartialView(plane);
        }

        // GET: PlaneController/Create
        public ActionResult Create()
        {
            ViewBag.PlaneType = new SelectList(Enum.GetNames(typeof(PlaneType)));
            return View();
        }

        // POST: PlaneController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Plane plane)
        {
            try
            {
                _planeService.Add(plane);
                _planeService.Commit();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: PlaneController/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var plane = _planeService.GetById((int)id);
            if (plane == null)
            {
                return NotFound();
            }
            ViewBag.PlaneType = new SelectList(Enum.GetNames(typeof(PlaneType)));
            return View(plane);
        }

        // POST: PlaneController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Plane plane)
        {
            try
            {
                _planeService.Update(plane);
                _planeService.Commit();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: PlaneController/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var plane = _planeService.GetById((int)id);
            if (plane == null)
            {
                return NotFound();
            }

            return View(plane);
        }

        // POST: PlaneController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            try
            {
                var plane = _planeService.GetById((int)id);
                _planeService.Delete(plane);
                _planeService.Commit();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

AM.UI.WEB/Views/Flight/Create.cshtml
@model AM.ApplicationCore.Domain.Flight

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Flight</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

             <div class="form-group">
                <label asp-for="Airline" class="control-label"></label>
                <input type="file" name="AirlineImage" class="form-control" />
               @* <span asp-validation-for="Airline" class="text-danger"></span>*@
            </div>

            <div class="form-group">
                <label asp-for="FlightDate" class="control-label"></label>
                <input asp-for="FlightDate" class="form-control" />
                <span asp-validation-for="FlightDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EstimatedDuration" class="control-label"></label>
                <input asp-for="EstimatedDuration" class="form-control" />
                <span asp-validation-for="EstimatedDuration" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EffectiveArrival" class="control-label"></label>
                <input asp-for="EffectiveArrival" class="form-control" />
                <span asp-validation-for="EffectiveArrival" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Departure" class="control-label"></label>
                <input asp-for="Departure" class="form-control" />
                <span asp-validation-for="Departure" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Destination" class="control-label"></label>
                <input asp-for="Destination" class="form-control" />
                <span asp-validation-for="Destination" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PlaneId" class="control-label"></label>
                <select asp-for="PlaneId" class="form-control" asp-items="ViewBag.Planes"></select>
                <span asp-validation-for="PlaneId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AM.UI.WEB/Views/Flight/Delete.cshtml
@model AM.ApplicationCore.Domain.Flight

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Flight</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Airline)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Airline)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FlightDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FlightDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EstimatedDuration)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EstimatedDuration)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EffectiveArrival)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EffectiveArrival)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Departure)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Departure)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Destination)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Destination)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Plane)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Plane.PlaneId)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="FlightId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

AM.UI.WEB/Views/Flight/Details.cshtml
@model AM.ApplicationCore.Domain.Flight

<div>
    <h4>Flight</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Airline)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Airline)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FlightDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FlightDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EstimatedDuration)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EstimatedDuration)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EffectiveArrival)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EffectiveArrival)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Departure)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Departure)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Destination)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Destination)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Plane)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Plane.PlaneId)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.FlightId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

AM.UI.WEB/Views/Flight/Edit.cshtml
@model AM.ApplicationCore.Domain.Flight

<h4>Flight</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Airline" class="control-label"></label>
                <input asp-for="Airline" class="form-control" />
                <span asp-validation-for="Airline" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="FlightId" />
            <div class="form-group">
                <label asp-for="FlightDate" class="control-label"></label>
                <input asp-for="FlightDate" class="form-control" />
                <span asp-validation-for="FlightDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EstimatedDuration" class="control-label"></label>
                <input asp-for="EstimatedDuration" class="form-control" />
                <span asp-validation-for="EstimatedDuration" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EffectiveArrival" class="control-label"></label>
                <input asp-for="EffectiveArrival" class="form-control" />
                <span asp-validation-for="EffectiveArrival" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Departure" class="control-label"></label>
                <input asp-for="Departure" class="form-control" />
                <span asp-validation-for="Departure" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Destination" class="control-label"></label>
                <input asp-for="Destination" class="form-control" />
                <span asp-validation-for="Destination" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PlaneId" class="control-label"></label>
                <select asp-for="PlaneId" class="form-control" asp-items="ViewBag.Planes"></select>
                <span asp-validation-for="PlaneId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AM.UI.WEB/Views/Flight/Index.cshtml
@model IEnumerable<AM.ApplicationCore.Domain.Flight>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<form asp-action="index">
<fieldset>
    <legend> Recherche</legend>
    Saisir une date de départ : <input type="date" name="dateDepart" /> 
    <input type="submit" value="Recherchez" />
</fieldset>
</form>


<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Airline)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FlightId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FlightDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EstimatedDuration)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EffectiveArrival)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Departure)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Destination)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PlaneId)
            </th>
    @*        <th>
                @Html.DisplayNameFor(model => model.Pilot)
            </th>*@
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
               @* @Html.DisplayFor(modelItem => item.Airline)*@
               <img src="~/uploads/@item.Airline" width="50" height="50">
            </td>
            <td >
                @Html.DisplayFor(modelItem => item.FlightId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FlightDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EstimatedDuration)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EffectiveArrival)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Departure)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Destination)
            </td>
            <td>
              @*  @Html.DisplayFor(modelItem => item.PlaneId)*@
              <a asp-controller="Plane" asp-action="_Details" asp-route-id=@item.PlaneId> @item.Plane.Information</a>
            </td>

            <td>
                    @Html.ActionLink("Edit", "Edit", new {  id=item.FlightId  }) |
                    @Html.ActionLink("Details", "Details", new {  id=item.FlightId  }) |
                    @Html.ActionLink("Delete", "Delete", new {  id=item.FlightId  })
            </td>
        </tr>
        <tr>
            <td colspan="5">
                <partial name="_FlightDetails" model="item">
            </td>
        </tr>
}
    </tbody>
</table>

AM.UI.WEB/Views/Flight/_FlightDetails.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}