AM.UI.WEB/Controllers/FlightController.cs
using Microsoft.AspNetCore.Http;
using System.IO;

using Microsoft.AspNetCore.Mvc;
using AM.ApplicationCore.Interfaces;
using AM.ApplicationCore.Domain;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace AM.UI.WEB.Controllers
{
    public class FlightController : Controller
    {
        private readonly IServiceFlight _flightService;
        private readonly IServicePlane _planeService;

        public FlightController(IServiceFlight flightService,IServicePlane planeService)
        {
            _planeService = planeService;
            _flightService = flightService;
        }

        // GET: FlightController
        public ActionResult Index(DateTime? dateDepart)
        {

            if (dateDepart == null)
            {
                return View(_flightService.GetAll().ToList());
            }
            else
            {
                
                return View(_flightService.GetFlightByDate(((DateTime)dateDepart)));
            }
        }

        // GET: FlightController/Details/5
        public ActionResult Details(int id)
        {

            var flight = _flightService.GetById((int)id);
            if (flight == null)
            {
                return NotFound();
            }
            return View(flight);
        }

        // GET: FlightController/Create
        public ActionResult Create() { 
            ViewBag.Planes = new SelectList(_planeService.GetAll().ToList(),
                "PlaneId", "Information");
            return View();
        }

        // POST: FlightController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Flight flight, IFormFile AirlineImage)
        {
            
            try
            {
                if (AirlineImage != null)
                {
                    var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "uploads", AirlineImage.FileName);
                    Stream stream = new FileStream(path, FileMode.Create);
                    AirlineImage.CopyTo(stream);
                    flight.Airline = AirlineImage.FileName;
                }
                _flightService.Add(flight);
                _flightService.Commit();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: FlightController/Edit/5
        public ActionResult Edit(int? id)
        {
            
            if (id == null)
            {
                return NotFound();
            }

            var flight = _flightService.GetById((int)id);
            if (flight == null)
            {
                return NotFound();
            }
            
            ViewBag.Planes = new SelectList(_planeService.GetAll().ToList(),
                "PlaneId", "Information", flight.PlaneId);
            return View(flight);
        }

        // POST: FlightController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Flight flight)
        {
            try
            {
                _flightService.Update(flight);
                _flightService.Commit();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
           
        }

        // GET: FlightController/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var flight = _flightService.GetById((int)id);
            if (flight == null)
            {
                return NotFound();
            }

            return View(flight);
        }

        // POST: FlightController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            try
            {
                var flight = _flightService.GetById((int)id);
                _flightService.Delete(flight);
                _flightService.Commit();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

AM.UI.WEB/Controllers/PlaneController.cs
using AM.ApplicationCore.Domain;
using AM.ApplicationCore.Interfaces;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace AM.UI.WEB.Controllers
{
    public class PlaneController : Controller
    {
        private readonly IServicePlane _planeService;

        public PlaneController(IServicePlane planeService)
        {
            _planeService = planeService;
        }
        // GET: PlaneController
        public ActionResult Index()
        {
            //return View();

            List<Plane> listplane = _planeService.GetAll().ToList();
            foreach (var plane in listplane)
            {
                plane.NbrVols = _planeService.GetFlightNbre(plane);
            }

            return View(listplane);
        }

        // GET: PlaneController/Details/5
        public ActionResult Details(int id)
        {
            var plane = _planeService.GetById((int)id);
            if (plane == null)
            {
                return NotFound();
            }
            return View(plane);
        }

        public ActionResult _Details(int id)
        {
            var plane = _planeService.GetById((int)id);
            if (plane == null)
            {
                return NotFound();
            }
            return PartialView(plane);
        }

        // GET: PlaneController/Create
        public ActionResult Create()
        {
            ViewBag.PlaneType = new SelectList(Enum.GetNames(typeof(PlaneType)));
            return View();
        }

        // POST: PlaneController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Plane plane)
        {
            try
            {
                _planeService.Add(plane);
                _planeService.Commit();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: PlaneController/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var plane = _planeService.GetById((int)id);
            if (plane == null)
            {
                return NotFound();
            }
            ViewBag.PlaneType = new SelectList(Enum.GetNames(typeof(PlaneType)));
            return View(plane);
        }

        // POST: PlaneController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Plane plane)
        {
            try
            {
                _planeService.Update(plane);
                _planeService.Commit();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: PlaneController/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var plane = _planeService.GetById((int)id);
            if (plane == null)
            {
                return NotFound();
            }

            return View(plane);
        }

        // POST: PlaneController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            try
            {
                var plane = _planeService.GetById((int)id);
                _planeService.Delete(plane);
                _planeService.Commit();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

AM.UI.WEB/Views/Plane/Create.cshtml
@model AM.ApplicationCore.Domain.Plane

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Plane</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="PlaneType" class="control-label"></label>
                <select asp-for="PlaneType" class="form-control" asp-items="Html.GetEnumSelectList<AM.ApplicationCore.Domain.PlaneType>()"></select>
                <span asp-validation-for="PlaneType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ManufactureDate" class="control-label"></label>
                <input asp-for="ManufactureDate" class="form-control" />
                <span asp-validation-for="ManufactureDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Capacity" class="control-label"></label>
                <input asp-for="Capacity" class="form-control" />
                <span asp-validation-for="Capacity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AM.UI.WEB/Views/Plane/Delete.cshtml
@model AM.ApplicationCore.Domain.Plane

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Plane</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PlaneType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PlaneType)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ManufactureDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ManufactureDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Capacity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Capacity)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="PlaneId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

AM.UI.WEB/Views/Plane/Details.cshtml
@model AM.ApplicationCore.Domain.Plane

<div>
    <h4>Plane</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PlaneType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PlaneType)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ManufactureDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ManufactureDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Capacity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Capacity)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.PlaneId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

AM.UI.WEB/Views/Plane/Edit.cshtml
@model AM.ApplicationCore.Domain.Plane

<h4>Plane</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="PlaneId" />
            <div class="form-group">
                <label asp-for="PlaneType" class="control-label"></label>
                <select asp-for="PlaneType" class="form-control" asp-items="ViewBag.PlaneType"></select>
                <span asp-validation-for="PlaneType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ManufactureDate" class="control-label"></label>
                <input asp-for="ManufactureDate" class="form-control" />
                <span asp-validation-for="ManufactureDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Capacity" class="control-label"></label>
                <input asp-for="Capacity" class="form-control" />
                <span asp-validation-for="Capacity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AM.UI.WEB/Views/Plane/Index.cshtml
@model IEnumerable<AM.ApplicationCore.Domain.Plane>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.PlaneType)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ManufactureDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Capacity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NbrVols)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.PlaneType)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ManufactureDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Capacity)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NbrVols)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.PlaneId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.PlaneId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.PlaneId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

AM.UI.WEB/Views/Plane/_Details.cshtml
@model AM.ApplicationCore.Domain.Plane

<div>
    <h4>Plane</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PlaneType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PlaneType)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ManufactureDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ManufactureDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Capacity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Capacity)
        </dd>
    </dl>
</div>
<div>
    @*<a asp-action="Edit" asp-route-id="@Model?.PlaneId">Edit</a> |*@
     <a asp-controller="Flight" asp-action="Index">Back to List</a>

</div>